import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Package } from 'lucide-react';
import { useOrder } from '@/hooks/useOrders';
import Spinner from '@/components/ui/Spinner';
import { formatSelectedOptions } from '@/lib/variantDisplay';
const STATUS_STEPS = ['pending', 'confirmed', 'shipped', 'delivered'];
function paymentLabel(paymentMethod, paymentStatus) {
    if (paymentMethod === 'cod') {
        return paymentStatus === 'paid' ? 'COD collected' : 'Cash on delivery';
    }
    return paymentStatus;
}
export default function OrderDetailPage() {
    const { id } = useParams();
    const { data: order, isLoading, isError } = useOrder(Number(id));
    if (isLoading)
        return _jsx(Spinner, { className: "py-32" });
    if (isError || !order) {
        return (_jsxs("div", { className: "max-w-4xl mx-auto px-4 py-20 text-center text-gray-400", children: [_jsx("p", { className: "text-lg font-medium", children: "Order not found" }), _jsx(Link, { to: "/orders", className: "text-sm text-primary hover:underline mt-2 inline-block", children: "Back to Orders" })] }));
    }
    const currentStep = STATUS_STEPS.indexOf(order.status);
    const isCancelled = order.status === 'cancelled';
    return (_jsxs("div", { className: "max-w-4xl mx-auto px-3 sm:px-4 py-4 sm:py-8", children: [_jsxs(Link, { to: "/orders", className: "text-xs sm:text-sm text-gray-500 flex items-center gap-1 mb-4 sm:mb-6 hover:text-primary touch-target", children: [_jsx(ArrowLeft, { size: 16 }), " Back to Orders"] }), _jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4 sm:mb-6", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-xl sm:text-2xl font-bold", children: ["Order #", order.id] }), _jsxs("p", { className: "text-xs sm:text-sm text-gray-500 mt-0.5", children: ["Placed on ", new Date(order.created_at).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })] })] }), _jsxs("div", { className: "sm:text-right", children: [_jsxs("p", { className: "text-xl sm:text-2xl font-bold text-primary", children: ["\u20B9", order.total_amount.toFixed(0)] }), order.coupon_code && order.coupon_discount > 0 && (_jsxs("p", { className: "text-[10px] sm:text-xs text-emerald-600 font-medium mt-0.5", children: ["Coupon ", order.coupon_code, " \u00B7 \u2212\u20B9", order.coupon_discount.toFixed(0)] })), _jsxs("p", { className: `text-xs sm:text-sm font-medium capitalize ${order.payment_status === 'paid' ? 'text-green-600' :
                                    order.payment_status === 'failed' ? 'text-red-600' : 'text-yellow-600'}`, children: ["Payment: ", paymentLabel(order.payment_method, order.payment_status)] })] })] }), !isCancelled && (_jsx("div", { className: "bg-white rounded-xl sm:rounded-2xl border p-4 sm:p-6 mb-4 sm:mb-6", children: _jsx("div", { className: "flex items-center justify-between", children: STATUS_STEPS.map((step, i) => (_jsxs("div", { className: "flex-1 flex flex-col items-center relative", children: [_jsx("div", { className: `w-7 h-7 sm:w-8 sm:h-8 rounded-full flex items-center justify-center text-xs font-bold z-10 ${i <= currentStep ? 'bg-primary text-white' : 'bg-gray-200 text-gray-400'}`, children: i + 1 }), _jsx("span", { className: `text-[10px] sm:text-xs mt-1.5 sm:mt-2 capitalize ${i <= currentStep ? 'text-primary font-medium' : 'text-gray-400'}`, children: step }), i < STATUS_STEPS.length - 1 && (_jsx("div", { className: `absolute top-3.5 sm:top-4 left-1/2 w-full h-0.5 ${i < currentStep ? 'bg-primary' : 'bg-gray-200'}` }))] }, step))) }) })), isCancelled && (_jsx("div", { className: "bg-red-50 border border-red-200 rounded-xl sm:rounded-2xl p-4 sm:p-6 mb-4 sm:mb-6 text-center", children: _jsx("p", { className: "text-red-600 font-semibold text-sm sm:text-base", children: "This order has been cancelled." }) })), _jsxs("div", { className: "bg-white rounded-xl sm:rounded-2xl border p-4 sm:p-6", children: [_jsxs("h3", { className: "font-bold text-sm sm:text-base mb-3 sm:mb-4 flex items-center gap-2", children: [_jsx(Package, { size: 18, className: "text-primary" }), "Items (", order.items.length, ")"] }), _jsx("div", { className: "divide-y", children: order.items.map((item) => (_jsxs("div", { className: "flex items-center justify-between py-3", children: [_jsxs("div", { className: "flex items-center gap-3 min-w-0", children: [item.resolved_image_url && (_jsx("img", { src: item.resolved_image_url, alt: "", className: "w-14 h-14 rounded-lg object-cover shrink-0", loading: "lazy" })), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "font-medium text-sm", children: item.product_name || `Product #${item.product_id}` }), _jsxs("p", { className: "text-[10px] text-gray-400", children: ["Product ID: #", item.product_id] }), item.selected_options && (_jsx("p", { className: "text-xs text-gray-500", children: formatSelectedOptions(item.selected_options, null) })), _jsxs("p", { className: "text-xs text-gray-500", children: ["Qty: ", item.quantity, " \u00D7 \u20B9", item.unit_price] })] })] }), _jsxs("p", { className: "font-bold text-sm sm:text-base", children: ["\u20B9", (item.quantity * item.unit_price).toFixed(0)] })] }, item.id))) })] }), order.payment_id && (_jsxs("div", { className: "mt-3 sm:mt-4 bg-gray-50 rounded-xl p-3 sm:p-4 text-xs sm:text-sm text-gray-500", children: ["Payment ID: ", _jsx("span", { className: "font-mono break-all", children: order.payment_id })] }))] }));
}
